INSERT INTO `bukkit_enchantment` (`id`, `titleRu`, `titleEn`, `levelmax`) VALUES
  ("0", "Защита", "Protection", 127),
  ("1", "Огнестойкость", "Fire Protection", 127),
  ("3", "Взрывоустойчивость", "Blast Protection", 127),
  ("4", "Снарядостойкость", "Projectile Protection", 127),
  ("2", "Лёгкость", "Feather falling", 127),
  ("5", "Дыхание", "Respiration", 127),
  ("6", "Родство с водой", "Aqua Affinity", 127),
  ("7", "Шипы", "Thorns", 127),
  ("16", "Острота", "Sharpness", 127),
  ("17", "Небесная кара", "Smite", 127),
  ("18", "Бич членистоногих", "Bane of Arthropods", 127),
  ("19", "Отбрасывание", "Knockback", 127),
  ("20", "Аспект огня", "Fire aspect", 127),
  ("21", "Мародёрство", "Looting", 127),
  ("48", "Сила", "Power", 127),
  ("49", "Ударная волна", "Punch", 127),
  ("50", "Воспламенение", "Flame", 127),
  ("51", "Бесконечность", "Infinity", 127),
  ("32", "Эффективность", "Efficiency", 127),
  ("33", "Шёлковое касание", "Silk Touch", 127),
  ("34", "Неразрушимость", "Unbreaking", 127),
  ("35", "Удача", "Fortune", 127);
