INSERT INTO `bukkit_material` (`id`, `titleRu`, `titleEn`, `imageUrl`, `enchantability`) VALUES
  ("1", "Камень", "Stone", "http://media-mcw.cursecdn.com/a/a6/Grid_Stone.png", null),
  ("2", "Трава", "Grass Block", "http://media-mcw.cursecdn.com/6/6f/Grid_Grass.png", null),
  ("3", "Земля", "Dirt", "http://media-mcw.cursecdn.com/b/bd/Grid_Dirt.png", null),
  ("4", "Булыжник", "Cobblestone", "http://media-mcw.cursecdn.com/0/03/Grid_Cobblestone.png", null),
  ("7", "Коренная порода", "Bedrock", "http://media-mcw.cursecdn.com/e/e0/Grid_Bedrock.png", null),
  ("12", "Песок", "Sand", "http://media-mcw.cursecdn.com/b/bb/Grid_Sand.png", null),
  ("13", "Гравий", "Gravel", "http://media-mcw.cursecdn.com/0/03/Grid_Gravel.png", null),
  ("14", "Золотая руда", "Gold Ore", "http://media-mcw.cursecdn.com/5/5c/Grid_Gold_%28Ore%29.png", null),
  ("15", "Железная руда", "Iron Ore", "http://media-mcw.cursecdn.com/7/74/Grid_Iron_%28Ore%29.png", null),
  ("16", "Угольная руда", "Coal Ore", "http://media-mcw.cursecdn.com/8/8c/Grid_Coal_%28Ore%29.png", null),
  ("20", "Стекло", "Glass", "http://media-mcw.cursecdn.com/0/00/Grid_Glass.png", null),
  ("21", "Лазуритовая руда", "Lapis Lazuli Ore", "http://media-mcw.cursecdn.com/d/d2/Grid_Lapis_Lazuli_%28Ore%29.png", null),
  ("22", "Лазуритовый блок", "Lapis Lazuli Block", "http://media-mcw.cursecdn.com/5/58/Grid_Lapis_Lazuli_%28Block%29.png", null),
  ("23", "Раздатчик", "Dispenser", "http://media-mcw.cursecdn.com/c/cc/Grid_Dispenser.png", null),
  ("25", "Музыкальный блок", "Note Block", "http://media-mcw.cursecdn.com/1/1d/Grid_Note_Block.png", null),
  ("27", "Электрические рельсы", "Powered Rail", "http://media-mcw.cursecdn.com/9/9d/Grid_Powered_Rail.png", null),
  ("28", "Нажимные рельсы", "Detector Rail", "http://media-mcw.cursecdn.com/a/a2/Grid_Detector_Rail.png", null),
  ("29", "Липкий поршень", "Sticky Piston", "http://media-mcw.cursecdn.com/3/32/Grid_Sticky_Piston.png", null),
  ("30", "Паутина", "Cobweb", "http://media-mcw.cursecdn.com/3/36/Grid_Cobweb.png", null),
  ("32", "Сухой куст", "Dead Bush", "http://media-mcw.cursecdn.com/f/f6/Grid_Dead_Bush.png", null),
  ("33", "Поршень", "Piston", "http://media-mcw.cursecdn.com/3/3c/Grid_Piston.png", null),
  ("37", "Одуванчик", "Dandelion", "http://media-mcw.cursecdn.com/4/49/Grid_Dandelion.png", null),
  ("38", "Роза", "Rose", "http://media-mcw.cursecdn.com/4/49/Grid_Rose.png", null),
  ("39", "Коричневый гриб", "Brown Mushroom", "http://media-mcw.cursecdn.com/d/d8/Grid_Brown_Mushroom.png", null),
  ("40", "Красный гриб", "Red Mushroom", "http://media-mcw.cursecdn.com/0/01/Grid_Red_Mushroom.png", null),
  ("41", "Золотой блок", "Block of Gold", "http://media-mcw.cursecdn.com/b/b6/Grid_Gold_%28Block%29.png", null),
  ("42", "Железный блок", "Block of Iron", "http://media-mcw.cursecdn.com/5/5a/Grid_Iron_%28Block%29.png", null),
  ("45", "Кирпич", "Bricks", "http://media-mcw.cursecdn.com/6/64/Grid_Brick_%28Block%29.png", null),
  ("46", "ТНТ", "TNT", "http://media-mcw.cursecdn.com/2/2b/Grid_TNT.png", null),
  ("47", "Книжный шкаф", "Bookshelf", "http://media-mcw.cursecdn.com/b/bc/Grid_Bookshelf.png", null),
  ("48", "Замшелый булыжник", "Mossy Cobblestone", "http://media-mcw.cursecdn.com/7/7d/Grid_Moss_Stone.png", null),
  ("49", "Обсидиан", "Obsidian", "http://media-mcw.cursecdn.com/5/5d/Grid_Obsidian.png", null),
  ("50", "Факел", "Torch", "http://media-mcw.cursecdn.com/3/32/Grid_Torch.png", null),
  ("53", "Дубовые ступени", "Oak Wood Stairs", "http://media-mcw.cursecdn.com/3/3b/Grid_Wooden_Stairs.png", null),
  ("54", "Сундук", "Chest", "http://media-mcw.cursecdn.com/c/c1/Grid_Chest.png", null),
  ("56", "Алмазная руда", "Diamond Ore", "http://media-mcw.cursecdn.com/e/ef/Grid_Diamond_%28Ore%29.png", null),
  ("57", "Алмазный блок", "Block of Diamond", "http://media-mcw.cursecdn.com/7/73/Grid_Diamond_%28Block%29.png", null),
  ("58", "Верстак", "Crafting Table", "http://media-mcw.cursecdn.com/7/79/Grid_Crafting_Table.png", null),
  ("61", "Печь", "Furnace", "http://media-mcw.cursecdn.com/2/2e/Grid_Furnace.png", null),
  ("65", "Лестница", "Ladders", "http://media-mcw.cursecdn.com/9/99/Grid_Ladders.png", null),
  ("66", "Рельсы", "Rail", "http://media-mcw.cursecdn.com/7/7a/Grid_Rails.png", null),
  ("67", "Каменные ступени", "Cobblestone Stairs", "http://media-mcw.cursecdn.com/7/7f/Grid_Cobblestone_Stairs.png", null),
  ("69", "Рычаг", "Lever", "http://media-mcw.cursecdn.com/3/33/Grid_Lever.png", null),
  ("70", "Каменная нажимная пластина", "Stone Pressure Plate", "http://media-mcw.cursecdn.com/4/46/Grid_Stone_Pressure_Plate.png", null),
  ("72", "Деревянная нажимная пластина", "Wooden Pressure Plate", "http://media-mcw.cursecdn.com/d/d4/Grid_Wooden_Pressure_Plate.png", null),
  ("73", "Красная руда", "Redstone Ore", "http://media-mcw.cursecdn.com/b/b8/Grid_Redstone_%28Ore%29.png", null),
  ("76", "Красный факел", "Redstone Torch", "http://media-mcw.cursecdn.com/6/66/Grid_Redstone_%28Torch%29.png", null),
  ("77", "Каменная кнопка", "Stone Button", "http://media-mcw.cursecdn.com/8/81/Grid_Stone_Button.png", null),
  ("78", "Снег", "Snow", "http://media-mcw.cursecdn.com/6/6c/Grid_Snow.png", null),
  ("79", "Лед", "Ice", "http://media-mcw.cursecdn.com/2/2e/Grid_Ice.png", null),
  ("80", "Блок снега", "Snow Block", "http://media-mcw.cursecdn.com/6/66/Grid_Snow_%28Block%29.png", null),
  ("81", "Кактус", "Cactus", "http://media-mcw.cursecdn.com/f/fb/Grid_Cactus.png", null),
  ("82", "Блок глины", "Clay Block", "http://media-mcw.cursecdn.com/a/a6/Grid_Clay_%28Block%29.png", null),
  ("84", "Проигрыватель", "Jukebox", "http://media-mcw.cursecdn.com/1/10/Grid_Jukebox.png", null),
  ("85", "Забор", "Fence", "http://media-mcw.cursecdn.com/c/c8/Grid_Fence.png", null),
  ("86", "Тыква", "Pumpkin", "http://media-mcw.cursecdn.com/b/be/Grid_Pumpkin.png", null),
  ("87", "Адский камень", "Netherrack", "http://media-mcw.cursecdn.com/8/86/Grid_Netherrack.png", null),
  ("88", "Песок души", "Soul Sand", "http://media-mcw.cursecdn.com/e/e4/Grid_Soul_Sand.png", null),
  ("89", "Светящийся камень", "Glowstone", "http://media-mcw.cursecdn.com/f/fd/Grid_Glowstone_%28Block%29.png", null),
  ("91", "Светильник Джека", "Jack 'o' Lantern", "http://media-mcw.cursecdn.com/a/ac/Grid_Jack-O-Lantern.png", null),
  ("96", "Люк", "Trapdoor", "http://media-mcw.cursecdn.com/b/b2/Grid_Trapdoor.png", null),
  ("101", "Железная решетка", "Iron Bars", "http://media-mcw.cursecdn.com/0/00/Grid_Iron_Bars.png", null),
  ("102", "Стеклянная панель", "Glass Pane", "http://media-mcw.cursecdn.com/3/30/Grid_Glass_Pane.png", null),
  ("103", "Арбуз", "Melon (block)", "http://media-mcw.cursecdn.com/0/09/Grid_Melon_%28Block%29.png", null),
  ("106", "Лианы", "Vines", "http://media-mcw.cursecdn.com/2/29/Grid_Vines.png", null),
  ("107", "Ворота", "Fence Gate", "http://media-mcw.cursecdn.com/c/c2/Grid_Fence_Gate.png", null),
  ("108", "Ступени из кирпича", "Brick Stairs", "http://media-mcw.cursecdn.com/3/3c/Grid_Brick_Stairs.png", null),
  ("109", "Ступени из каменного кирпича", "Stone Brick Stairs", "http://media-mcw.cursecdn.com/a/af/Grid_Stone_Brick_Stairs.png", null),
  ("110", "Мицелий", "Mycelium", "http://media-mcw.cursecdn.com/a/aa/Grid_Mycelium.png", null),
  ("111", "Кувшинка", "Lily Pad", "http://media-mcw.cursecdn.com/4/49/Grid_Lily_Pad.png", null),
  ("112", "Адский кирпич", "Nether Brick", "http://media-mcw.cursecdn.com/6/62/Grid_Nether_Brick.png", null),
  ("113", "Адский забор", "Nether Brick Fence", "http://media-mcw.cursecdn.com/5/59/Grid_Nether_Brick_Fence.png", null),
  ("114", "Ступени из адского кирпича", "Nether Brick Stairs", "http://media-mcw.cursecdn.com/6/68/Grid_Nether_Brick_Stairs.png", null),
  ("116", "Стол зачаровывания", "Enchantment Table", "http://media-mcw.cursecdn.com/0/00/Grid_Enchantment_Table.png", null),
  ("121", "Камень Края", "End Stone", "http://media-mcw.cursecdn.com/1/1e/Grid_White_Stone.png", null),
  ("122", "Яйцо дракона", "Dragon Egg", "http://media-mcw.cursecdn.com/b/b1/Grid_Dragon_Egg.png", null),
  ("123", "Лампа", "Redstone Lamp", "http://media-mcw.cursecdn.com/f/fa/Grid_Redstone_Lamp.png", null),
  ("128", "Ступени из песчаника", "Sandstone Stairs", "http://media-mcw.cursecdn.com/0/0d/Grid_Sandstone_Stairs.png", null),
  ("129", "Изумрудная руда", "Emerald Ore", "http://media-mcw.cursecdn.com/e/e7/Grid_Emerald_Ore.png", null),
  ("130", "Сундук Края", "Ender Chest", "http://media-mcw.cursecdn.com/5/56/Grid_Ender_Chest.png", null),
  ("131", "Натяжной датчик", "Tripwire Hook", "http://media-mcw.cursecdn.com/9/90/Grid_Tripwire_Hook.png", null),
  ("133", "Изумрудный блок", "Block of Emerald", "http://media-mcw.cursecdn.com/2/27/Grid_Block_of_Emerald.png", null),
  ("134", "Сосновые ступени", "Spruce Wood Stairs", "http://media-mcw.cursecdn.com/2/24/Grid_Spruce_Wood_Stairs.png", null),
  ("135", "Березовые ступени", "Birch Wood Stairs", "http://media-mcw.cursecdn.com/d/de/Grid_Birch_Wood_Stairs.png", null),
  ("136", "Тропические ступени", "Jungle Wood Stairs", "http://media-mcw.cursecdn.com/b/b9/Grid_Jungle_Wood_Stairs.png", null),
  ("138", "Маяк", "Beacon", "http://media-mcw.cursecdn.com/c/cb/Grid_Beacon.png", null),
  ("143", "Деревянная кнопка", "Wooden Button", "http://media-mcw.cursecdn.com/c/c6/Grid_Wooden_Button.png", null),
  ("145", "Наковальня", "Anvil", "http://media-mcw.cursecdn.com/1/13/Grid_Anvil.png", null),
  ("146", "Сундук-ловушка", "Trapped Chest", "http://media-mcw.cursecdn.com/b/bb/Grid_Trapped_Chest.png", null),
  ("147", "Утяжеленная нажимная пластина (легкая)", "Weighted Pressure Plate (Light)", "http://media-mcw.cursecdn.com/b/b9/Grid_Weighted_Pressure_Plate_%28Light%29.png", null),
  ("148", "Утяжеленная нажимная пластина (тяжелая)", "Weighted Pressure Plate (Heavy)", "http://media-mcw.cursecdn.com/6/65/Grid_Weighted_Pressure_Plate_%28Heavy%29.png", null),
  ("151", "Датчик дневного света", "Daylight Sensor", "http://media-mcw.cursecdn.com/1/18/Grid_Daylight_Sensor.png", null),
  ("152", "Блок красного камня", "Block of Redstone", "http://media-mcw.cursecdn.com/2/2e/Grid_Block_of_Redstone.png", null),
  ("153", "Кварц Нижнего мира (руда)", "Nether Quartz Ore", "http://media-mcw.cursecdn.com/8/82/Grid_Nether_Quartz_Ore.png", null),
  ("154", "Загрузочная воронка", "Hopper", "http://media-mcw.cursecdn.com/c/cb/Grid_Hopper.png", null),
  ("156", "Кварцевые ступени", "Quartz Stairs", "http://media-mcw.cursecdn.com/c/c5/Grid_Quartz_Stairs.png", null),
  ("157", "Активирующие рельсы", "Activator Rail", "http://media-mcw.cursecdn.com/5/50/Grid_Activator_Rail.png", null),
  ("158", "Выбрасыватель", "Dropper", "http://media-mcw.cursecdn.com/7/7f/Grid_Dropper.png", null),
  ("170", "Сноп сена", "Hay Block", "http://media-mcw.cursecdn.com/1/1f/Grid_Hay_Bale.png", null),
  ("172", "Обожженная глина", "Hardened Clay", "http://media-mcw.cursecdn.com/6/6d/Grid_Hardened_Clay.png", null),
  ("173", "Угольный блок", "Block of Coal", "http://media-mcw.cursecdn.com/b/b2/Grid_Block_of_Coal.png", null),
  ("256", "Железная лопата", "Iron Shovel", "http://media-mcw.cursecdn.com/0/01/Grid_Iron_Shovel.png", "14"),
  ("257", "Железная кирка", "Iron Pickaxe", "http://media-mcw.cursecdn.com/1/1d/Grid_Iron_Pickaxe.png", "14"),
  ("258", "Железный топор", "Iron Axe", "http://media-mcw.cursecdn.com/1/1d/Grid_Iron_Axe.png", "14"),
  ("259", "Огниво", "Flint and Steel", "http://media-mcw.cursecdn.com/f/fb/Grid_Flint_and_Steel.png", "1"),
  ("260", "Красное яблоко", "Apple", "http://media-mcw.cursecdn.com/3/39/Grid_Red_Apple.png", null),
  ("261", "Лук", "Bow", "http://media-mcw.cursecdn.com/4/49/Grid_Bow.png", "1"),
  ("262", "Стрела", "Arrow", "http://media-mcw.cursecdn.com/c/cc/Grid_Arrow.png", null),
  ("264", "Алмаз", "Diamond", "http://media-mcw.cursecdn.com/c/cf/Grid_Diamond_%28Gem%29.png", null),
  ("265", "Железный слиток", "Iron Ingot", "http://media-mcw.cursecdn.com/c/c6/Grid_Iron_%28Ingot%29.png", null),
  ("266", "Золотой слиток", "Gold Ingot", "http://media-mcw.cursecdn.com/6/62/Grid_Gold_%28Ingot%29.png", null),
  ("267", "Железный меч", "Iron Sword", "http://media-mcw.cursecdn.com/d/d5/Grid_Iron_Sword.png", "14"),
  ("268", "Деревянный меч", "Wooden Sword", "http://media-mcw.cursecdn.com/c/cf/Grid_Wooden_Sword.png", "15"),
  ("269", "Деревянная лопата", "Wooden Shovel", "http://media-mcw.cursecdn.com/2/21/Grid_Wooden_Shovel.png", "15"),
  ("270", "Деревянная кирка", "Wooden Pickaxe", "http://media-mcw.cursecdn.com/3/3d/Grid_Wooden_Pickaxe.png", "15"),
  ("271", "Деревянный топор", "Wooden Axe", "http://media-mcw.cursecdn.com/2/2a/Grid_Wooden_Axe.png", "15"),
  ("272", "Каменный меч", "Stone Sword", "http://media-mcw.cursecdn.com/e/e1/Grid_Stone_Sword.png", "5"),
  ("273", "Каменная лопата", "Stone Shovel", "http://media-mcw.cursecdn.com/f/ff/Grid_Stone_Shovel.png", "5"),
  ("274", "Каменная кирка", "Stone Pickaxe", "http://media-mcw.cursecdn.com/d/d2/Grid_Stone_Pickaxe.png", "5"),
  ("275", "Каменный топор", "Stone Axe", "http://media-mcw.cursecdn.com/5/55/Grid_Stone_Axe.png", "5"),
  ("276", "Алмазный меч", "Diamond Sword", "http://media-mcw.cursecdn.com/8/81/Grid_Diamond_Sword.png", "10"),
  ("277", "Алмазная лопата", "Diamond Shovel", "http://media-mcw.cursecdn.com/8/8e/Grid_Diamond_Shovel.png", "10"),
  ("278", "Алмазная кирка", "Diamond Pickaxe", "http://media-mcw.cursecdn.com/c/ce/Grid_Diamond_Pickaxe.png", "10"),
  ("279", "Алмазный топор", "Diamond Axe", "http://media-mcw.cursecdn.com/8/8d/Grid_Diamond_Axe.png", "10"),
  ("280", "Палка", "Stick", "http://media-mcw.cursecdn.com/e/e9/Grid_Stick.png", null),
  ("281", "Чашка", "Bowl", "http://media-mcw.cursecdn.com/f/f1/Grid_Bowl.png", null),
  ("282", "Тушеные грибы", "Mushroom Stew", "http://media-mcw.cursecdn.com/f/fd/Grid_Mushroom_Stew.png", null),
  ("283", "Золотой меч", "Golden Sword", "http://media-mcw.cursecdn.com/1/1f/Grid_Gold_Sword.png", "22"),
  ("284", "Золотая лопата", "Golden Shovel", "http://media-mcw.cursecdn.com/8/85/Grid_Gold_Shovel.png", "22"),
  ("285", "Золотая кирка", "Golden Pickaxe", "http://media-mcw.cursecdn.com/9/95/Grid_Gold_Pickaxe.png", "22"),
  ("286", "Золотой топор", "Golden Axe", "http://media-mcw.cursecdn.com/9/99/Grid_Gold_Axe.png", "22"),
  ("287", "Нить", "String", "http://media-mcw.cursecdn.com/f/fa/Grid_String.png", null),
  ("288", "Перо", "Feather", "http://media-mcw.cursecdn.com/a/a7/Grid_Feather.png", null),
  ("289", "Порох", "Gunpowder", "http://media-mcw.cursecdn.com/7/7a/Grid_Gunpowder.png", null),
  ("290", "Деревянная мотыга", "Wooden Hoe", "http://media-mcw.cursecdn.com/e/ea/Grid_Wooden_Hoe.png", "15"),
  ("291", "Каменная мотыга", "Stone Hoe", "http://media-mcw.cursecdn.com/b/ba/Grid_Stone_Hoe.png", "5"),
  ("292", "Железная мотыга", "Iron Hoe", "http://media-mcw.cursecdn.com/f/f8/Grid_Iron_Hoe.png", "14"),
  ("293", "Алмазная мотыга", "Diamond Hoe", "http://media-mcw.cursecdn.com/c/c9/Grid_Diamond_Hoe.png", "11"),
  ("294", "Золотая мотыга", "Golden Hoe", "http://media-mcw.cursecdn.com/7/77/Grid_Gold_Hoe.png", "22"),
  ("295", "Семена пшеницы", "Seeds", "http://media-mcw.cursecdn.com/6/68/Grid_Seeds.png", null),
  ("296", "Пшеница", "Wheat", "http://media-mcw.cursecdn.com/c/c4/Grid_Wheat.png", null),
  ("297", "Хлеб", "Bread", "http://media-mcw.cursecdn.com/d/d4/Grid_Bread.png", null),
  ("298", "Кожаный шлем", "Leather Cap", "http://media-mcw.cursecdn.com/2/24/Grid_Leather_Cap.png", "15"),
  ("299", "Кожаная туника", "Leather Tunic", "http://media-mcw.cursecdn.com/e/ed/Grid_Leather_Tunic.png", "15"),
  ("300", "Кожаные штаны", "Leather Pants", "http://media-mcw.cursecdn.com/c/ce/Grid_Leather_Pants.png", "15"),
  ("301", "Кожаные ботинки", "Leather Boots", "http://media-mcw.cursecdn.com/0/06/Grid_Leather_Boots.png", "15"),
  ("302", "Кольчужный шлем", "Chain Helmet", "http://media-mcw.cursecdn.com/c/cf/Grid_Chain_Armor_Helmet.png", "12"),
  ("303", "Кольчужная кираса", "Chain Chestplate", "http://media-mcw.cursecdn.com/f/f4/Grid_Chain_Armor_Chestplate.png", "12"),
  ("304", "Кольчужные поножи", "Chain Leggings", "http://media-mcw.cursecdn.com/1/1b/Grid_Chain_Armor_Leggings.png", "12"),
  ("305", "Кольчужные ботинки", "Chain Boots", "http://media-mcw.cursecdn.com/7/74/Grid_Chain_Armor_Boots.png", "12"),
  ("306", "Железный шлем", "Iron Helmet", "http://media-mcw.cursecdn.com/e/ec/Grid_Iron_Helmet.png", "9"),
  ("307", "Железная кираса", "Iron Chestplate", "http://media-mcw.cursecdn.com/8/8d/Grid_Iron_Chestplate.png", "9"),
  ("308", "Железные поножи", "Iron Leggings", "http://media-mcw.cursecdn.com/9/99/Grid_Iron_Leggings.png", "9"),
  ("309", "Железные ботинки", "Iron Boots", "http://media-mcw.cursecdn.com/f/f5/Grid_Iron_Boots.png", "9"),
  ("310", "Алмазный шлем", "Diamond Helmet", "http://media-mcw.cursecdn.com/b/bd/Grid_Diamond_Helmet.png", "10"),
  ("311", "Алмазная кираса", "Diamond Chestplate", "http://media-mcw.cursecdn.com/e/e7/Grid_Diamond_Chestplate.png", "10"),
  ("312", "Алмазные поножи", "Diamond Leggings", "http://media-mcw.cursecdn.com/e/e3/Grid_Diamond_Leggings.png", "10"),
  ("313", "Алмазные ботинки", "Diamond Boots", "http://media-mcw.cursecdn.com/d/d1/Grid_Diamond_Boots.png", "10"),
  ("314", "Золотой шлем", "Golden Helmet", "http://media-mcw.cursecdn.com/3/3a/Grid_Gold_Helmet.png", "25"),
  ("315", "Золотая кираса", "Golden Chestplate", "http://media-mcw.cursecdn.com/7/7b/Grid_Gold_Chestplate.png", "25"),
  ("316", "Золотые поножи", "Golden Leggings", "http://media-mcw.cursecdn.com/f/f5/Grid_Gold_Leggings.png", "25"),
  ("317", "Золотые ботинки", "Golden Boots", "http://media-mcw.cursecdn.com/0/00/Grid_Gold_Boots.png", "25"),
  ("318", "Кремень", "Flint", "http://media-mcw.cursecdn.com/8/82/Grid_Flint.png", null),
  ("319", "Сырая свинина", "Raw Porkchop", "http://media-mcw.cursecdn.com/e/ec/Grid_Raw_Porkchop.png", null),
  ("320", "Жареная свинина", "Cooked Porkchop", "http://media-mcw.cursecdn.com/b/bd/Grid_Cooked_Porkchop.png", null),
  ("321", "Картина", "Painting", "http://media-mcw.cursecdn.com/c/cc/Grid_Painting.png", null),
  ("323", "Табличка", "Sign", "http://media-mcw.cursecdn.com/0/06/Grid_Sign.png", null),
  ("324", "Деревянная дверь", "Wooden Door", "http://media-mcw.cursecdn.com/c/cd/Grid_Wooden_Door.png", null),
  ("325", "Ведро", "Bucket", "http://media-mcw.cursecdn.com/2/2a/Grid_Bucket.png", null),
  ("326", "Ведро воды", "Water Bucket", "http://media-mcw.cursecdn.com/b/bf/Grid_Water_Bucket.png", null),
  ("327", "Ведро лавы", "Lava Bucket", "http://media-mcw.cursecdn.com/c/cf/Grid_Lava_Bucket.png", null),
  ("328", "Вагонетка", "Minecart", "http://media-mcw.cursecdn.com/5/58/Grid_Minecart.png", null),
  ("329", "Седло", "Saddle", "http://media-mcw.cursecdn.com/0/09/Grid_Saddle.png", null),
  ("330", "Железная дверь", "Iron Door", "http://media-mcw.cursecdn.com/2/27/Grid_Iron_Door.png", null),
  ("331", "Красная пыль", "Redstone", "http://media-mcw.cursecdn.com/c/c3/Grid_Redstone_%28Dust%29.png", null),
  ("332", "Снежок", "Snowball", "http://media-mcw.cursecdn.com/6/67/Grid_Snowball.png", null),
  ("333", "Лодка", "Boat", "http://media-mcw.cursecdn.com/5/59/Grid_Boat.png", null),
  ("334", "Кожа", "Leather", "http://media-mcw.cursecdn.com/6/66/Grid_Leather.png", null),
  ("335", "Молоко", "Milk", "http://media-mcw.cursecdn.com/6/63/Grid_Milk_Bucket.png", null),
  ("336", "Кирпич", "Brick", "http://media-mcw.cursecdn.com/e/ed/Grid_Clay_%28Brick%29.png", null),
  ("337", "Глина", "Clay", "http://media-mcw.cursecdn.com/3/38/Grid_Clay_%28Item%29.png", null),
  ("338", "Сахарный тростник", "Sugar Cane", "http://media-mcw.cursecdn.com/d/d3/Grid_Sugar_Cane.png", null),
  ("339", "Бумага", "Paper", "http://media-mcw.cursecdn.com/6/6c/Grid_Paper.png", null),
  ("340", "Книга", "Book", "http://media-mcw.cursecdn.com/e/ec/Grid_Book.png", "1"),
  ("341", "Слизь", "Slimeball", "http://media-mcw.cursecdn.com/c/c9/Grid_Slimeball.png", null),
  ("342", "Вагонетка с сундуком", "Minecart with Chest", "http://media-mcw.cursecdn.com/f/fa/Grid_Storage_Minecart.png", null),
  ("343", "Вагонетка с двигателем", "Minecart with Furnace", "http://media-mcw.cursecdn.com/7/7f/Grid_Powered_Minecart.png", null),
  ("344", "Яйцо", "Egg", "http://media-mcw.cursecdn.com/2/27/Grid_Egg.png", null),
  ("345", "Компас", "Compass", "http://media-mcw.cursecdn.com/f/f2/Grid_Compass.png", null),
  ("346", "Удочка", "Fishing Rod", "http://media-mcw.cursecdn.com/c/c7/Grid_Fishing_Rod.png", "1"),
  ("347", "Часы", "Clock", "http://media-mcw.cursecdn.com/3/32/Grid_Clock.png", null),
  ("348", "Светопыль", "Glowstone Dust", "http://media-mcw.cursecdn.com/2/2c/Grid_Glowstone_%28Dust%29.png", null),
  ("349", "Сырая рыба", "Raw Fish", "http://media-mcw.cursecdn.com/6/6a/Grid_Raw_Fish.png", null),
  ("350", "Жареная рыба", "Cooked Fish", "http://media-mcw.cursecdn.com/2/29/Grid_Cooked_Fish.png", null),
  ("352", "Кость", "Bone", "http://media-mcw.cursecdn.com/e/e8/Grid_Bone.png", null),
  ("353", "Сахар", "Sugar", "http://media-mcw.cursecdn.com/9/96/Grid_Sugar.png", null),
  ("354", "Торт", "Cake", "http://media-mcw.cursecdn.com/2/28/Grid_Cake.png", null),
  ("355", "Кровать", "Bed", "http://media-mcw.cursecdn.com/a/a3/Grid_Bed.png", null),
  ("356", "Красный повторитель", "Redstone Repeater", "http://media-mcw.cursecdn.com/e/e6/Grid_Redstone_Repeater.png", null),
  ("357", "Печенье", "Cookie", "http://media-mcw.cursecdn.com/9/95/Grid_Cookie.png", null),
  ("359", "Ножницы", "Shears", "http://media-mcw.cursecdn.com/1/13/Grid_Shears.png", "1"),
  ("360", "Ломтик арбуза", "Melon", "http://media-mcw.cursecdn.com/e/ee/Grid_Melon_%28Slice%29.png", null),
  ("361", "Семена тыквы", "Pumpkin Seeds", "http://media-mcw.cursecdn.com/7/72/Grid_Pumpkin_Seeds.png", null),
  ("362", "Семена арбуза", "Melon Seeds", "http://media-mcw.cursecdn.com/7/75/Grid_Melon_Seeds.png", null),
  ("363", "Сырая говядина", "Raw Beef", "http://media-mcw.cursecdn.com/6/61/Grid_Raw_Beef.png", null),
  ("364", "Жареная говядина", "Steak", "http://media-mcw.cursecdn.com/d/da/Grid_Steak.png", null),
  ("365", "Сырая курятина", "Raw Chicken", "http://media-mcw.cursecdn.com/e/e5/Grid_Raw_Chicken.png", null),
  ("366", "Жареная курятина", "Cooked Chicken", "http://media-mcw.cursecdn.com/2/2e/Grid_Cooked_Chicken.png", null),
  ("367", "Гнилая плоть", "Rotten Flesh", "http://media-mcw.cursecdn.com/3/33/Grid_Rotten_Flesh.png", null),
  ("368", "Жемчуг Края", "Ender Pearl", "http://media-mcw.cursecdn.com/1/13/Grid_Ender_Pearl.png", null),
  ("369", "Огненный стержень", "Blaze Rod", "http://media-mcw.cursecdn.com/1/18/Grid_Blaze_Rod.png", null),
  ("370", "Слеза гаста", "Ghast Tear", "http://media-mcw.cursecdn.com/6/66/Grid_Ghast_Tear.png", null),
  ("371", "Золотой самородок", "Gold Nugget", "http://media-mcw.cursecdn.com/1/1d/Grid_Gold_Nugget.png", null),
  ("372", "Адский нарост", "Nether Wart", "http://media-mcw.cursecdn.com/f/f2/Grid_Nether_Wart_Seeds.png", null),
  ("374", "Колба", "Glass Bottle", "http://media-mcw.cursecdn.com/2/22/Grid_Glass_Bottle.png", null),
  ("375", "Паучий глаз", "Spider Eye", "http://media-mcw.cursecdn.com/0/03/Grid_Spider_Eye.png", null),
  ("376", "Приготовленный паучий глаз", "Fermented Spider Eye", "http://media-mcw.cursecdn.com/2/29/Grid_Fermented_Spider_Eye.png", null),
  ("377", "Огненный порошок", "Blaze Powder", "http://media-mcw.cursecdn.com/0/09/Grid_Blaze_Powder.png", null),
  ("378", "Лавовый крем", "Magma Cream", "http://media-mcw.cursecdn.com/e/e8/Grid_Magma_Cream.png", null),
  ("379", "Варочная стойка", "Brewing Stand", "http://media-mcw.cursecdn.com/7/70/Grid_Brewing_Stand.png", null),
  ("380", "Котел", "Cauldron", "http://media-mcw.cursecdn.com/c/ca/Grid_Cauldron.png", null),
  ("381", "Око Края", "Eye of Ender", "http://media-mcw.cursecdn.com/0/0e/Grid_Eye_of_Ender.png", null),
  ("382", "Сверкающий ломтик арбуза", "Glistering Melon", "http://media-mcw.cursecdn.com/1/11/Grid_Glistering_Melon.png", null),
  ("384", "Зелье опыта", "Bottle of Enchanting", "http://media-mcw.cursecdn.com/b/bf/Grid_Bottle_o%27_Enchanting.png", null),
  ("385", "Огненный шар", "Fire Charge", "http://media-mcw.cursecdn.com/e/e1/Grid_Fire_Charge.png", null),
  ("386", "Книга с пером", "Book and Quill", "http://media-mcw.cursecdn.com/e/eb/Grid_Book_and_Quill.png", null),
  ("387", "Написанная книга", "Written Book", "http://media-mcw.cursecdn.com/c/c5/Grid_Written_Book.png", null),
  ("388", "Изумруд", "Emerald", "http://media-mcw.cursecdn.com/8/87/Grid_Emerald.png", null),
  ("389", "Рамка", "Item Frame", "http://media-mcw.cursecdn.com/c/c5/Grid_Item_Frame.png", null),
  ("390", "Цветочный горшок", "Flower Pot", "http://media-mcw.cursecdn.com/8/89/Grid_Flower_Pot.png", null),
  ("391", "Морковь", "Carrot", "http://media-mcw.cursecdn.com/8/8b/Grid_Carrot.png", null),
  ("392", "Картофель", "Potato", "http://media-mcw.cursecdn.com/2/2b/Grid_Potato.png", null),
  ("393", "Печеный картофель", "Baked Potato", "http://media-mcw.cursecdn.com/6/6c/Grid_Baked_Potato.png", null),
  ("394", "Ядовитый картофель", "Poisonous Potato", "http://media-mcw.cursecdn.com/f/fd/Grid_Poisonous_Potato.png", null),
  ("395", "Карта", "Empty Map", "http://media-mcw.cursecdn.com/c/c7/Grid_Empty_Map.png", null),
  ("396", "Золотая морковь", "Golden Carrot", "http://media-mcw.cursecdn.com/a/a7/Grid_Golden_Carrot.png", null),
  ("398", "Удочка с морковью", "Carrot on a Stick", "http://media-mcw.cursecdn.com/e/e4/Grid_Carrot_on_a_Stick.png", "1"),
  ("399", "Звезда Нижнего мира", "Nether Star", "http://media-mcw.cursecdn.com/a/ae/Grid_Nether_Star.png", null),
  ("400", "Тыквенный пирог", "Pumpkin Pie", "http://media-mcw.cursecdn.com/9/9f/Grid_Pumpkin_Pie.png", null),
  ("401", "Ракета", "Firework Rocket", "http://media-mcw.cursecdn.com/1/12/Grid_Fireworks.png", null),
  ("403", "Зачарованная книга", "Enchanted Book", "http://media-mcw.cursecdn.com/f/f7/Grid_Enchanted_Book.png", "1"),
  ("404", "Компаратор", "Redstone Comparator", "http://media-mcw.cursecdn.com/e/ea/Grid_Redstone_Comparator.png", null),
  ("405", "Адский кирпич", "Nether Brick", "http://media-mcw.cursecdn.com/7/71/Grid_Nether_Brick_%28Item%29.png", null),
  ("406", "Кварц Нижнего мира", "Nether Quartz", "http://media-mcw.cursecdn.com/2/2b/Grid_Nether_Quartz.png", null),
  ("407", "Вагонетка с ТНТ", "Minecart with TNT", "http://media-mcw.cursecdn.com/9/93/Grid_Minecart_with_TNT.png", null),
  ("408", "Вагонетка с воронкой", "Minecart with Hopper", "http://media-mcw.cursecdn.com/7/78/Grid_Minecart_with_Hopper.png", null),
  ("417", "Железная конская броня", "Iron Horse Armor", "http://media-mcw.cursecdn.com/a/af/Grid_Iron_Horse_Armor.png", null),
  ("418", "Золотая конская броня", "Gold Horse Armor", "http://media-mcw.cursecdn.com/0/09/Grid_Golden_Horse_Armor.png", null),
  ("419", "Алмазная конская броня", "Diamond Horse Armor", "http://media-mcw.cursecdn.com/a/af/Grid_Diamond_Horse_Armor.png", null),
  ("420", "Поводок", "Lead", "http://media-mcw.cursecdn.com/3/37/Grid_Leash.png", null),
  ("421", "Бирка", "Name Tag", "http://media-mcw.cursecdn.com/9/97/Grid_Name_Tag.png", null),
  ("2256", "Пластинка 13", "13 Disc", "http://media-mcw.cursecdn.com/5/55/Grid_Gold_Disc.png", null),
  ("2257", "Пластинка Cat", "Cat Disc", "http://media-mcw.cursecdn.com/c/c4/Grid_Green_Disc.png", null),
  ("2258", "Пластинка Blocks", "Blocks Disc", "http://media-mcw.cursecdn.com/4/4d/Grid_Blocks_Disc.png", null),
  ("2259", "Пластинка Chirp", "Chirp Disc", "http://media-mcw.cursecdn.com/b/be/Grid_Chirp_Disc.png", null),
  ("2260", "Пластинка Far", "Far Disc", "http://media-mcw.cursecdn.com/9/9e/Grid_Far_Disc.png", null),
  ("2261", "Пластинка Mall", "Mall Disc", "http://media-mcw.cursecdn.com/b/b8/Grid_Mall_Disc.png", null),
  ("2262", "Пластинка Mellohi", "Mellohi Disc", "http://media-mcw.cursecdn.com/7/7a/Grid_Mellohi_Disc.png", null),
  ("2263", "Пластинка Stal", "Stal Disc", "http://media-mcw.cursecdn.com/1/1d/Grid_Stal_Disc.png", null),
  ("2264", "Пластинка Strad", "Strad Disc", "http://media-mcw.cursecdn.com/a/aa/Grid_Strad_Disc.png", null),
  ("2265", "Пластинка Ward", "Ward Disc", "http://media-mcw.cursecdn.com/d/da/Grid_Ward_Disc.png", null),
  ("2266", "Пластинка 11", "11 Disc", "http://media-mcw.cursecdn.com/e/e4/Grid_11_Disc.png", null),
  ("2267", "Пластинка Wait", "Wait Disc", "http://media-mcw.cursecdn.com/6/67/Grid_wait_Disc.png", null),
  ("5:0", "Дубовые доски", "Oak Wood Planks", "http://media-mcw.cursecdn.com/9/9f/Grid_Wooden_Plank.png", null),
  ("5:1", "Сосновые доски", "Spruce Wood Planks", "http://media-mcw.cursecdn.com/b/bb/Grid_Wooden_Plank_%28Pine%29.png", null),
  ("5:2", "Березовые доски", "Birch Wood Planks", "http://media-mcw.cursecdn.com/0/01/Grid_Wooden_Plank_%28Birch%29.png", null),
  ("5:3", "Тропические доски", "Jungle Wood Planks", "http://media-mcw.cursecdn.com/2/2a/Grid_Wooden_Plank_%28Jungle%29.png", null),
  ("6:0", "Дубовый саженец", "Oak Sapling", "http://media-mcw.cursecdn.com/b/b5/Grid_Sapling.png", null),
  ("6:1", "Сосновый саженец", "Spruce Sapling", "http://media-mcw.cursecdn.com/c/c6/Grid_Sapling_Spruce.png", null),
  ("6:2", "Березовый саженец", "Birch Sapling", "http://media-mcw.cursecdn.com/b/b4/Grid_Sapling_Birch.png", null),
  ("6:3", "Тропический саженец", "Jungle Sapling", "http://media-mcw.cursecdn.com/7/7f/Grid_Sapling_Jungle.png", null),
  ("17:0", "Дубовая древесина", "Oak Wood", "http://media-mcw.cursecdn.com/b/bf/Grid_Wood.png", null),
  ("17:1", "Сосновая древесина", "Spruce Wood", "http://media-mcw.cursecdn.com/d/db/Grid_Wood_%28Pine%29.png", null),
  ("17:2", "Березовая древесина", "Birch Wood", "http://media-mcw.cursecdn.com/8/81/Grid_Wood_%28Birch%29.png", null),
  ("17:3", "Тропическая древесина", "Jungle Wood", "http://media-mcw.cursecdn.com/5/5e/Grid_Wood_%28Jungle%29.png", null),
  ("18:0", "Дубовая листва", "Oak Leaves", "http://media-mcw.cursecdn.com/3/30/Grid_Leaves.png", null),
  ("18:1", "Сосновая листва", "Spruce Leaves", "http://media-mcw.cursecdn.com/0/08/Grid_Leaves_%28Pine%29.png", null),
  ("18:2", "Березовая листва", "Birch Leaves", "http://media-mcw.cursecdn.com/0/0a/Grid_Leaves_%28Birch%29.png", null),
  ("18:3", "Тропическая листва", "Jungle Leaves", "http://media-mcw.cursecdn.com/1/1b/Grid_Leaves_%28Jungle%29.png", null),
  ("24:0", "Песчаник", "Sandstone", "http://media-mcw.cursecdn.com/1/12/Grid_Sandstone.png", null),
  ("24:1", "Резной песчаник", "Chiseled sandstone", "http://media-mcw.cursecdn.com/1/1b/Grid_Decorative_Sandstone.png", null),
  ("24:2", "Гладкий песчаник", "Smooth sandstone", "http://media-mcw.cursecdn.com/2/22/Grid_Smooth_Sandstone.png", null),
  ("31:1", "Высокая трава", "Tall Grass", "http://media-mcw.cursecdn.com/c/c1/Grid_Tall_Grass2.png", null),
  ("31:2", "Высокая трава", "Tall Grass (Fern)", "http://media-mcw.cursecdn.com/e/e1/Grid_Tall_Grass3.png", null),
  ("35:0", "Белая шерсть", "White Wool", "http://media-mcw.cursecdn.com/f/fa/Grid_White_Wool.png", null),
  ("35:1", "Оранжевая шерсть", "Orange Wool", "http://media-mcw.cursecdn.com/0/07/Grid_Orange_Wool.png", null),
  ("35:2", "Сиреневая шерсть", "Magenta Wool", "http://media-mcw.cursecdn.com/f/fd/Grid_Magenta_Wool.png", null),
  ("35:3", "Светло-синяя шерсть", "Light Blue Wool", "http://media-mcw.cursecdn.com/f/fb/Grid_Light_Blue_Wool.png", null),
  ("35:4", "Желтая шерсть", "Yellow Wool", "http://media-mcw.cursecdn.com/e/ed/Grid_Yellow_Wool.png", null),
  ("35:5", "Светло-зеленая шерсть", "Lime Wool", "http://media-mcw.cursecdn.com/a/a2/Grid_Lime_Wool.png", null),
  ("35:6", "Розовая шерсть", "Pink Wool", "http://media-mcw.cursecdn.com/b/b3/Grid_Pink_Wool.png", null),
  ("35:7", "Серая шерсть", "Gray Wool", "http://media-mcw.cursecdn.com/d/d3/Grid_Gray_Wool.png", null),
  ("35:8", "Светло-серая шерсть", "Light Gray", "http://media-mcw.cursecdn.com/e/e5/Grid_Light_Gray_Wool.png", null),
  ("35:9", "Бирюзовая шерсть", "Cyan Wool", "http://media-mcw.cursecdn.com/c/cd/Grid_Cyan_Wool.png", null),
  ("35:10", "Фиолетовая шерсть", "Purple Wool", "http://media-mcw.cursecdn.com/5/51/Grid_Purple_Wool.png", null),
  ("35:11", "Синяя шерсть", "Blue Wool", "http://media-mcw.cursecdn.com/4/40/Grid_Blue_Wool.png", null),
  ("35:12", "Коричневая шерсть", "Brown Wool", "http://media-mcw.cursecdn.com/2/2a/Grid_Brown_Wool.png", null),
  ("35:13", "Зеленая шерсть", "Green Wool", "http://media-mcw.cursecdn.com/f/fa/Grid_Green_Wool.png", null),
  ("35:14", "Красная шерсть", "Red Wool", "http://media-mcw.cursecdn.com/2/2a/Grid_Red_Wool.png", null),
  ("35:15", "Черная шерсть", "Black Wool", "http://media-mcw.cursecdn.com/4/45/Grid_Black_Wool.png", null),
  ("44:0", "Каменная плита", "Stone Slab", "http://media-mcw.cursecdn.com/2/29/Grid_Stone_Slab.png", null),
  ("44:1", "Песчаниковая плита", "Sandstone Slab", "http://media-mcw.cursecdn.com/2/2a/Grid_Sandstone_Slab.png", null),
  ("44:3", "Булыжниковая плита", "Cobblestone Slab", "http://media-mcw.cursecdn.com/f/f7/Grid_Cobblestone_Slab.png", null),
  ("44:4", "Кирпичная плита", "Brick Slab", "http://media-mcw.cursecdn.com/b/b3/Grid_Bricks_Slab.png", null),
  ("44:5", "Каменнокирпичная плита", "Stone Brick Slab", "http://media-mcw.cursecdn.com/4/46/Grid_Stone_Bricks_Slab.png", null),
  ("44:6", "Плита из адского кирпича", "Nether Brick Slab", "http://media-mcw.cursecdn.com/d/dd/Grid_Nether_Brick_Slab.png", null),
  ("44:7", "Кварцевая плита", "Quartz Slab", "http://media-mcw.cursecdn.com/0/09/Grid_Quartz_Slab.png", null),
  ("98:0", "Каменный кирпич", "Stone Bricks", "http://media-mcw.cursecdn.com/1/1c/Grid_Stone_Brick.png", null),
  ("98:1", "Потресканный каменный кирпич", "Cracked Stone Brick", "http://media-mcw.cursecdn.com/8/85/Grid_Cracked_Stone_Brick.png", null),
  ("98:2", "Замшелый каменный кирпич", "Mossy Stone Brick", "http://media-mcw.cursecdn.com/2/23/Grid_Mossy_Stone_Brick.png", null),
  ("98:3", "Резной каменный кирпич", "Chiseled Stone Brick", "http://media-mcw.cursecdn.com/7/7b/Grid_Chiseled_Stone_Brick.png", null),
  ("126:0", "Дубовая плита", "Oak Wood Slab", "http://media-mcw.cursecdn.com/5/5c/Grid_Oak_Wood_Slab.png", null),
  ("126:1", "Сосновая плита", "Spruce Wood Slab", "http://media-mcw.cursecdn.com/6/60/Grid_Spruce_Wood_Slab.png", null),
  ("126:2", "Березовая плита", "Birch Wood Slab", "http://media-mcw.cursecdn.com/b/bc/Grid_Birch_Wood_Slab.png", null),
  ("126:3", "Тропическая плита", "Jungle Wood Slab", "http://media-mcw.cursecdn.com/3/3f/Grid_Jungle_Wood_Slab.png", null),
  ("139:0", "Cтена из булыжника", "Cobblestone Wall", "http://media-mcw.cursecdn.com/a/a9/Grid_Cobblestone_Wall.png", null),
  ("139:1", "Cтена из замшелого булыжника", "Mossy Cobblestone Wall", "http://media-mcw.cursecdn.com/6/63/Grid_Mossy_Cobblestone_Wall.png", null),
  ("155:0", "Кварцевый блок", "Quartz Block", "http://media-mcw.cursecdn.com/0/04/Grid_Block_of_Quartz.png", null),
  ("155:1", "Резной кварцевый блок", "Chiseled Quartz Block", "http://media-mcw.cursecdn.com/8/8d/Grid_Chiseled_Quartz_Block.png", null),
  ("155:2", "Кварцевый пилон", "Pillar Quartz Block", "http://media-mcw.cursecdn.com/5/59/Grid_Pillar_Quartz_Block.png", null),
  ("159:0", "Белая обожженная глина", "White Stained Clay", "http://media-mcw.cursecdn.com/6/6b/Grid_White_Stained_Clay.png", null),
  ("159:1", "Оранжевая обожженная глина", "Orange Stained Clay", "http://media-mcw.cursecdn.com/3/3c/Grid_Orange_Stained_Clay.png", null),
  ("159:2", "Белая обожженная глина", "Magenta Stained Clay", "http://media-mcw.cursecdn.com/c/ce/Grid_Magenta_Stained_Clay.png", null),
  ("159:3", "Светло-синяя обожженная глина", "Light Blue Stained Clay", "http://media-mcw.cursecdn.com/a/a0/Grid_Light_Blue_Stained_Clay.png", null),
  ("159:4", "Желтая обожженная глина", "Yellow Stained Clay", "http://media-mcw.cursecdn.com/e/ef/Grid_Yellow_Stained_Clay.png", null),
  ("159:5", "Светло-зеленая обожженная глина", "Lime Stained Clay", "http://media-mcw.cursecdn.com/a/aa/Grid_Lime_Stained_Clay.png", null),
  ("159:6", "Розовая обожженная глина", "Pink Stained Clay", "http://media-mcw.cursecdn.com/6/68/Grid_Pink_Stained_Clay.png", null),
  ("159:7", "Серая обожженная глина", "Gray Stained Clay", "http://media-mcw.cursecdn.com/1/18/Grid_Gray_Stained_Clay.png", null),
  ("159:8", "Светло-серая обожженная глина", "Light Gray Stained Clay", "http://media-mcw.cursecdn.com/4/47/Grid_Light_Gray_Stained_Clay.png", null),
  ("159:9", "Бирюзовая обожженная глина", "Cyan Stained Clay", "http://media-mcw.cursecdn.com/7/78/Grid_Cyan_Stained_Clay.png", null),
  ("159:10", "Фиолетовая обожженная глина", "Purple Stained Clay", "http://media-mcw.cursecdn.com/6/6a/Grid_Purple_Stained_Clay.png", null),
  ("159:11", "Синяя обожженная глина", "Blue Stained Clay", "http://media-mcw.cursecdn.com/9/91/Grid_Blue_Stained_Clay.png", null),
  ("159:12", "Коричневая обожженная глина", "Brown Stained Clay", "http://media-mcw.cursecdn.com/2/20/Grid_Brown_Stained_Clay.png", null),
  ("159:13", "Зеленая обожженная глина", "Green Stained Clay", "http://media-mcw.cursecdn.com/1/19/Grid_Green_Stained_Clay.png", null),
  ("159:14", "Красная обожженная глина", "Red Stained Clay", "http://media-mcw.cursecdn.com/c/cd/Grid_Red_Stained_Clay.png", null),
  ("159:15", "Черная обожженная глина", "Black Stained Clay", "http://media-mcw.cursecdn.com/9/91/Grid_Black_Stained_Clay.png", null),
  ("171:0", "Белый ковер", "White Carpet", "http://media-mcw.cursecdn.com/7/72/Grid_White_Carpet.png", null),
  ("171:1", "Оранжевый ковер", "Orange Carpet", "http://media-mcw.cursecdn.com/3/3c/Grid_Orange_Carpet.png", null),
  ("171:2", "Сиреневый ковер", "Magenta Carpet", "http://media-mcw.cursecdn.com/0/01/Grid_Magenta_Carpet.png", null),
  ("171:3", "Светло-синий ковер", "Light Blue Carpet", "http://media-mcw.cursecdn.com/4/4b/Grid_Light_Blue_Carpet.png", null),
  ("171:4", "Желтый ковер", "Yellow Carpet", "http://media-mcw.cursecdn.com/6/63/Grid_Yellow_Carpet.png", null),
  ("171:5", "null", "Lime Carpet", "http://media-mcw.cursecdn.com/3/34/Grid_Lime_Carpet.png", null),
  ("171:6", "Светло-зеленый ковер", "Pink Carpet", "http://media-mcw.cursecdn.com/b/be/Grid_Pink_Carpet.png", null),
  ("171:7", "Серый ковер", "Gray Carpet", "http://media-mcw.cursecdn.com/2/2b/Grid_Gray_Carpet.png", null),
  ("171:8", "Светло-серый ковер", "Light Gray Carpet", "http://media-mcw.cursecdn.com/3/3a/Grid_Light_Gray_Carpet.png", null),
  ("171:9", "Бирюзовый ковер", "Cyan Carpet", "http://media-mcw.cursecdn.com/d/d4/Grid_Cyan_Carpet.png", null),
  ("171:10", "Фиолетовый ковер", "Purple Carpet", "http://media-mcw.cursecdn.com/5/55/Grid_Purple_Carpet.png", null),
  ("171:11", "Синий ковер", "Blue Carpet", "http://media-mcw.cursecdn.com/5/5a/Grid_Blue_Carpet.png", null),
  ("171:12", "Коричневый ковер", "Brown Carpet", "http://media-mcw.cursecdn.com/a/ad/Grid_Brown_Carpet.png", null),
  ("171:13", "Зеленый ковер", "Green Carpet", "http://media-mcw.cursecdn.com/4/41/Grid_Green_Carpet.png", null),
  ("171:14", "Красный ковер", "Red Carpet", "http://media-mcw.cursecdn.com/d/dc/Grid_Red_Carpet.png", null),
  ("171:15", "Черный ковер", "Black Carpet", "http://media-mcw.cursecdn.com/e/e6/Grid_Black_Carpet.png", null),
  ("263:0", "Уголь", "Coal", "http://media-mcw.cursecdn.com/1/1c/Grid_Coal_%28Item%29.png", null),
  ("263:1", "Древесный уголь", "Charcoal", "http://media-mcw.cursecdn.com/5/54/Grid_Charcoal_%28Item%29.png", null),
  ("322:0", "Золотое яблоко", "Golden Apple", "http://media-mcw.cursecdn.com/4/4e/Grid_Golden_Apple.png", null),
  ("322:1", "Зачарованное золотое яблоко", "Enchanted Golden Apple", "http://media-mcw.cursecdn.com/4/4e/Grid_Golden_Apple.png", null),
  ("351:0", "Чернильный мешок", "Ink Sac", "http://media-mcw.cursecdn.com/d/d6/Grid_Ink_Sac.png", null),
  ("351:1", "Цвет розы", "Rose Red", "http://media-mcw.cursecdn.com/0/0d/Grid_Rose_Red.png", null),
  ("351:2", "Кактусовая зелень", "Cactus Green", "http://media-mcw.cursecdn.com/f/fd/Grid_Cactus_Green.png", null),
  ("351:3", "Какао-бобы", "Cocoa Beans", "http://media-mcw.cursecdn.com/7/7d/Grid_Cocoa_Beans.png", null),
  ("351:4", "Ультрамарин", "Lapis Lazuli", "http://media-mcw.cursecdn.com/a/a8/Grid_Lapis_Lazuli_%28Dye%29.png", null),
  ("351:5", "Фиолетовый краситель", "Purple Dye", "http://media-mcw.cursecdn.com/a/a0/Grid_Purple_Dye.png", null),
  ("351:6", "Бирюзовый краситель", "Cyan Dye", "http://media-mcw.cursecdn.com/c/ca/Grid_Cyan_Dye.png", null),
  ("351:7", "Светло-серый краситель", "Light Gray Dye", "http://media-mcw.cursecdn.com/1/16/Grid_Light_Gray_Dye.png", null),
  ("351:8", "Серый краситель", "Gray Dye", "http://media-mcw.cursecdn.com/5/54/Grid_Gray_Dye.png", null),
  ("351:9", "Розовый краситель", "Pink Dye", "http://media-mcw.cursecdn.com/b/bb/Grid_Pink_Dye.png", null),
  ("351:10", "Лаймовый краситель", "Lime Dye", "http://media-mcw.cursecdn.com/a/a6/Grid_Lime_Dye.png", null),
  ("351:11", "Желтый одуванчиковый", "Dandelion Yellow", "http://media-mcw.cursecdn.com/d/df/Grid_Dandelion_Yellow.png", null),
  ("351:12", "Светло-синий краситель", "Light Blue Dye", "http://media-mcw.cursecdn.com/a/ae/Grid_Light_Blue_Dye.png", null),
  ("351:13", "Сиреневый краситель", "Magenta Dye", "http://media-mcw.cursecdn.com/8/8f/Grid_Magenta_Dye.png", null),
  ("351:14", "Оранжевый краситель", "Orange Dye", "http://media-mcw.cursecdn.com/b/b2/Grid_Orange_Dye.png", null),
  ("351:15", "Костная мука", "Bone Meal", "http://media-mcw.cursecdn.com/c/c0/Grid_Bone_Meal.png", null),
  ("373:0", "Колба воды", "Water Bottle", "http://media-mcw.cursecdn.com/9/97/Grid_Water_Bottle.png", null),
  ("373:16", "Грубое зелье", "Awkward Potion", "http://media-mcw.cursecdn.com/c/c3/Grid_Awkward_Potion.png", null),
  ("373:32", "Густое зелье", "Thick Potion", "http://media-mcw.cursecdn.com/e/e6/Grid_Thick_Potion.png", null),
  ("373:64", "Непримечательное усиленное зелье", "Mundane Extended Potion", "http://media-mcw.cursecdn.com/6/6c/Grid_Mundane_Potion.png", null),
  ("373:8192", "Непримечательное зелье", "Mundane Potion", "http://media-mcw.cursecdn.com/6/6c/Grid_Mundane_Potion.png", null),
  ("373:8193", "Зелье регенерации (0:45)", "Potion of Regeneration (0:45)", "http://media-mcw.cursecdn.com/0/00/Grid_Potion_of_Regeneration.png", null),
  ("373:8194", "Зелье ускорения (3:00)", "Potion of Swiftness (3:00)", "http://media-mcw.cursecdn.com/1/1c/Grid_Potion_of_Swiftness.png", null),
  ("373:8195", "Зелье огнестойкости (3:00)", "Potion of Fire Resistance (3:00)", "http://media-mcw.cursecdn.com/4/43/Grid_Potion_of_Fire_Resistance.png", null),
  ("373:8196", "Зелье отравления (0:45)", "Potion of Poison (0:45)", "http://media-mcw.cursecdn.com/a/a1/Grid_Potion_of_Poison.png", null),
  ("373:8197", "Зелье лечения", "Potion of Healing", "http://media-mcw.cursecdn.com/a/a3/Grid_Potion_of_Healing.png", null),
  ("373:8198", "Зелье ночного зрения (3:00)", "Potion of Night Vision (3:00)", "http://media-mcw.cursecdn.com/b/ba/Grid_Potion_of_Night_Vision.png", null),
  ("373:8200", "Зелье слабости (1:30)", "Potion of Weakness (1:30)", "http://media-mcw.cursecdn.com/2/2c/Grid_Potion_of_Weakness.png", null),
  ("373:8201", "Зелье силы (3:00)", "Potion of Strength (3:00)", "http://media-mcw.cursecdn.com/8/8c/Grid_Potion_of_Strength.png", null),
  ("373:8202", "Зелье замедления (1:30)", "Potion of Slowness (1:30)", "http://media-mcw.cursecdn.com/c/ca/Grid_Potion_of_Slowness.png", null),
  ("373:8204", "Зелье урона", "Potion of Harming", "http://media-mcw.cursecdn.com/b/b2/Grid_Potion_of_Harming.png", null),
  ("373:8206", "Зелье невидимости (3:00)", "Potion of Invisibility (3:00)", "http://media-mcw.cursecdn.com/d/d8/Grid_Potion_of_Invisibility.png", null),
  ("373:8225", "Зелье регенерации II (0:22)", "Potion of Regeneration II (0:22)", "http://media-mcw.cursecdn.com/0/00/Grid_Potion_of_Regeneration.png", null),
  ("373:8226", "Зелье ускорения II (1:30)", "Potion of Swiftness II (1:30)", "http://media-mcw.cursecdn.com/1/1c/Grid_Potion_of_Swiftness.png", null),
  ("373:8228", "Зелье отравления II (0:22)", "Potion of Poison II (0:22)", "http://media-mcw.cursecdn.com/a/a1/Grid_Potion_of_Poison.png", null),
  ("373:8229", "Зелье лечения II", "Potion of Healing II", "http://media-mcw.cursecdn.com/a/a3/Grid_Potion_of_Healing.png", null),
  ("373:8233", "Зелье силы II (1:30)", "Potion of Strength II (1:30)", "http://media-mcw.cursecdn.com/8/8c/Grid_Potion_of_Strength.png", null),
  ("373:8236", "Зелье урона II", "Potion of Harming II", "http://media-mcw.cursecdn.com/b/b2/Grid_Potion_of_Harming.png", null),
  ("373:8257", "Зелье регенерации (2:00)", "Potion of Regeneration (2:00)", "http://media-mcw.cursecdn.com/0/00/Grid_Potion_of_Regeneration.png", null),
  ("373:8258", "Зелье ускорения (8:00)", "Potion of Swiftness (8:00)", "http://media-mcw.cursecdn.com/1/1c/Grid_Potion_of_Swiftness.png", null),
  ("373:8259", "Зелье огнестойкости (8:00)", "Potion of Fire Resistance (8:00)", "http://media-mcw.cursecdn.com/4/43/Grid_Potion_of_Fire_Resistance.png", null),
  ("373:8260", "Зелье отравления (2:00)", "Potion of Poison (2:00)", "http://media-mcw.cursecdn.com/a/a1/Grid_Potion_of_Poison.png", null),
  ("373:8262", "Зелье ночного зрения (8:00)", "Potion of Night Vision (8:00)", "http://media-mcw.cursecdn.com/b/ba/Grid_Potion_of_Night_Vision.png", null),
  ("373:8264", "Зелье слабости (4:00)", "Potion of Weakness (4:00)", "http://media-mcw.cursecdn.com/2/2c/Grid_Potion_of_Weakness.png", null),
  ("373:8265", "Зелье силы (8:00)", "Potion of Strength (8:00)", "http://media-mcw.cursecdn.com/8/8c/Grid_Potion_of_Strength.png", null),
  ("373:8266", "Зелье замедления (4:00)", "Potion of Slowness (4:00)", "http://media-mcw.cursecdn.com/c/ca/Grid_Potion_of_Slowness.png", null),
  ("373:8270", "Зелье невидимости (8:00)", "Potion of Invisibility (8:00)", "http://media-mcw.cursecdn.com/d/d8/Grid_Potion_of_Invisibility.png", null),
  ("373:8289", "Зелье регенерации II (1:00)", "Potion of Regeneration II (1:00)", "http://media-mcw.cursecdn.com/0/00/Grid_Potion_of_Regeneration.png", null),
  ("373:8290", "Зелье ускорения II (4:00)", "Potion of Swiftness II (4:00)", "http://media-mcw.cursecdn.com/1/1c/Grid_Potion_of_Swiftness.png", null),
  ("373:8292", "Зелье отравления II (1:00)", "Potion of Poison II (1:00)", "http://media-mcw.cursecdn.com/a/a1/Grid_Potion_of_Poison.png", null),
  ("373:8297", "Зелье силы II (4:00)", "Potion of Strength II (4:00)", "http://media-mcw.cursecdn.com/8/8c/Grid_Potion_of_Strength.png", null),
  ("373:16384", "Взрывающееся непримечательное зелье", "Splash Mundane Potion", "http://media-mcw.cursecdn.com/0/0b/Grid_Splash_Mundane_Potion.png", null),
  ("373:16385", "Взрывающееся зелье регенерации (0:33)", "Splash Potion of Regeneration (0:33)", "http://media-mcw.cursecdn.com/0/0f/Grid_Splash_Potion_of_Regeneration.png", null),
  ("373:16386", "Взрывающееся зелье ускорения (2:15)", "Splash Potion of Swiftness (2:15)", "http://media-mcw.cursecdn.com/7/7a/Grid_Splash_Potion_of_Swiftness.png", null),
  ("373:16387", "Взрывающееся зелье огнестойкости (2:15)", "Splash Potion of Fire Resistance (2:15)", "http://media-mcw.cursecdn.com/c/cb/Grid_Splash_Potion_of_Fire_Resistance.png", null),
  ("373:16388", "Взрывающееся зелье отравления (0:33)", "Splash Potion of Poison (0:33)", "http://media-mcw.cursecdn.com/1/11/Grid_Splash_Potion_of_Poison.png", null),
  ("373:16389", "Взрывающееся зелье лечения", "Splash Potion of Healing", "http://media-mcw.cursecdn.com/3/33/Grid_Splash_Potion_of_Healing.png", null),
  ("373:16390", "Взрывающееся зелье ночного зрения (2:15)", "Splash Potion of Night Vision (2:15)", "http://media-mcw.cursecdn.com/c/c3/Grid_Splash_Potion_of_Night_Vision.png", null),
  ("373:16392", "Взрывающееся зелье слабости (1:07)", "Splash Potion of Weakness (1:07)", "http://media-mcw.cursecdn.com/9/94/Grid_Splash_Potion_of_Weakness.png", null),
  ("373:16393", "Взрывающееся зелье силы (2:15)", "Splash Potion of Strength (2:15)", "http://media-mcw.cursecdn.com/3/38/Grid_Splash_Potion_of_Strength.png", null),
  ("373:16394", "Взрывающееся зелье замедления (1:07)", "Splash Potion of Slowness (1:07)", "http://media-mcw.cursecdn.com/2/22/Grid_Splash_Potion_of_Slowness.png", null),
  ("373:16396", "Взрывающееся зелье урона", "Splash Potion of Harming", "http://media-mcw.cursecdn.com/5/52/Grid_Splash_Potion_of_Harming.png", null),
  ("373:16398", "Взрывающееся зелье невидимости (2:15)", "Splash Potion of Invisibility (2:15)", "http://media-mcw.cursecdn.com/8/89/Grid_Splash_Potion_of_Invisibility.png", null),
  ("373:16417", "Взрывающееся зелье регенерации II (0:16)", "Splash Potion of Regeneration II (0:16)", "http://media-mcw.cursecdn.com/0/0f/Grid_Splash_Potion_of_Regeneration.png", null),
  ("373:16418", "Взрывающееся зелье ускорения II (1:07)", "Splash Potion of Swiftness II (1:07)", "http://media-mcw.cursecdn.com/7/7a/Grid_Splash_Potion_of_Swiftness.png", null),
  ("373:16420", "Взрывающееся зелье отравления II (0:16)", "Splash Potion of Poison II (0:16)", "http://media-mcw.cursecdn.com/1/11/Grid_Splash_Potion_of_Poison.png", null),
  ("373:16421", "Взрывающееся зелье лечения II", "Splash Potion of Healing II", "http://media-mcw.cursecdn.com/3/33/Grid_Splash_Potion_of_Healing.png", null),
  ("373:16425", "Взрывающееся зелье силы II (1:07)", "Splash Potion of Strength II (1:07)", "http://media-mcw.cursecdn.com/3/38/Grid_Splash_Potion_of_Strength.png", null),
  ("373:16428", "Взрывающееся зелье урона II", "Splash Potion of Harming II", "http://media-mcw.cursecdn.com/5/52/Grid_Splash_Potion_of_Harming.png", null),
  ("373:16449", "Взрывающееся зелье регенерации (1:30)", "Splash Potion of Regeneration (1:30)", "http://media-mcw.cursecdn.com/0/0f/Grid_Splash_Potion_of_Regeneration.png", null),
  ("373:16450", "Взрывающееся зелье ускорения (6:00)", "Splash Potion of Swiftness (6:00)", "http://media-mcw.cursecdn.com/7/7a/Grid_Splash_Potion_of_Swiftness.png", null),
  ("373:16451", "Взрывающееся зелье огнестойкости (6:00)", "Splash Potion of Fire Resistance (6:00)", "http://media-mcw.cursecdn.com/c/cb/Grid_Splash_Potion_of_Fire_Resistance.png", null),
  ("373:16452", "Взрывающееся зелье отравления (1:30)", "Splash Potion of Poison (1:30)", "http://media-mcw.cursecdn.com/1/11/Grid_Splash_Potion_of_Poison.png", null),
  ("373:16454", "Взрывающееся зелье ночного зрения (6:00)", "Splash Potion of Night Vision (6:00)", "http://media-mcw.cursecdn.com/c/c3/Grid_Splash_Potion_of_Night_Vision.png", null),
  ("373:16456", "Взрывающееся зелье слабости (3:00)", "Splash Potion of Weakness (3:00)", "http://media-mcw.cursecdn.com/9/94/Grid_Splash_Potion_of_Weakness.png", null),
  ("373:16457", "Взрывающееся зелье силы (6:00)", "Splash Potion of Strength (6:00)", "http://media-mcw.cursecdn.com/3/38/Grid_Splash_Potion_of_Strength.png", null),
  ("373:16458", "Взрывающееся зелье замедления (3:00)", "Splash Potion of Slowness (3:00)", "http://media-mcw.cursecdn.com/2/22/Grid_Splash_Potion_of_Slowness.png", null),
  ("373:16462", "Взрывающееся зелье невидимости (6:00)", "Splash Potion of Invisibility (6:00)", "http://media-mcw.cursecdn.com/8/89/Grid_Splash_Potion_of_Invisibility.png", null),
  ("373:16481", "Взрывающееся зелье регенерации II (0:45)", "Splash Potion of Regeneration II (0:45)", "http://media-mcw.cursecdn.com/0/0f/Grid_Splash_Potion_of_Regeneration.png", null),
  ("373:16482", "Взрывающееся зелье ускорения II (3:00)", "Splash Potion of Swiftness II (3:00)", "http://media-mcw.cursecdn.com/7/7a/Grid_Splash_Potion_of_Swiftness.png", null),
  ("373:16484", "Взрывающееся зелье отравления II (0:45)", "Splash Potion of Poison II (0:45)", "http://media-mcw.cursecdn.com/1/11/Grid_Splash_Potion_of_Poison.png", null),
  ("373:16489", "Взрывающееся зелье силы II (3:00)", "Splash Potion of Strength II (3:00)", "http://media-mcw.cursecdn.com/3/38/Grid_Splash_Potion_of_Strength.png", null),
  ("383:50", "Яйцо призывания крипера", "Creeper Egg", "http://media-mcw.cursecdn.com/f/fc/Grid_Spawn_Creeper.png", null),
  ("383:51", "Яйцо призывания скелета", "Skeleton Egg", "http://media-mcw.cursecdn.com/3/35/Grid_Spawn_Skeleton.png", null),
  ("383:52", "Яйцо призывания паука", "Spider Egg", "http://media-mcw.cursecdn.com/5/50/Grid_Spawn_Spider.png", null),
  ("383:54", "Яйцо призывания зомби", "Zombie Egg", "http://media-mcw.cursecdn.com/3/30/Grid_Spawn_Zombie.png", null),
  ("383:55", "Яйцо призывания слизня", "Slime Egg", "http://media-mcw.cursecdn.com/1/11/Grid_Spawn_Slime.png", null),
  ("383:56", "Яйцо призывания гаста", "Ghast Egg", "http://media-mcw.cursecdn.com/3/3f/Grid_Spawn_Ghast.png", null),
  ("383:57", "Яйцо призывания зомби-свиночеловека", "Zombie Pigman Egg", "http://media-mcw.cursecdn.com/7/7b/Grid_Spawn_Pig_Zombie.png", null),
  ("383:58", "Яйцо призывания странника Края", "Enderman Egg", "http://media-mcw.cursecdn.com/6/62/Grid_Spawn_Enderman.png", null),
  ("383:59", "Яйцо призывания пещерного паука", "Cave Spider Egg", "http://media-mcw.cursecdn.com/e/ee/Grid_Spawn_Cave_Spider.png", null),
  ("383:60", "Яйцо призывания чейшуйницы", "Silverfish Egg", "http://media-mcw.cursecdn.com/1/11/Grid_Spawn_Silverfish.png", null),
  ("383:61", "Яйцо призывания ифрита", "Blaze Egg", "http://media-mcw.cursecdn.com/f/ff/Grid_Spawn_Blaze.png", null),
  ("383:62", "Яйцо призывания лавового куба", "Magma Cube Egg", "http://media-mcw.cursecdn.com/2/25/Grid_Spawn_Magma_Cube.png", null),
  ("383:65", "Яйцо призывания летучей мыши", "Bat Egg", "http://media-mcw.cursecdn.com/f/f3/Grid_Spawn_Bat.png", null),
  ("383:66", "Яйцо призывания ведьмы", "Witch Egg", "http://media-mcw.cursecdn.com/7/7c/Grid_Spawn_Witch.png", null),
  ("383:90", "Яйцо призывания свиньи", "Pig Egg", "http://media-mcw.cursecdn.com/0/09/Grid_Spawn_Pig.png", null),
  ("383:91", "Яйцо призывания овцы", "Sheep Egg", "http://media-mcw.cursecdn.com/f/f8/Grid_Spawn_Sheep.png", null),
  ("383:92", "Яйцо призывания коровы", "Cow Egg", "http://media-mcw.cursecdn.com/8/80/Grid_Spawn_Cow.png", null),
  ("383:93", "Яйцо призывания курицы", "Chicken Egg", "http://media-mcw.cursecdn.com/b/b0/Grid_Spawn_Chicken.png", null),
  ("383:94", "Яйцо призывания спрута", "Squid Egg", "http://media-mcw.cursecdn.com/5/58/Grid_Spawn_Squid.png", null),
  ("383:95", "Яйцо призывания волка", "Wolf Egg", "http://media-mcw.cursecdn.com/4/4b/Grid_Spawn_Wolf.png", null),
  ("383:96", "Яйцо призывания грибной коровы", "Mooshroom Egg", "http://media-mcw.cursecdn.com/9/91/Grid_Spawn_Mooshroom.png", null),
  ("383:98", "Яйцо призывания оцелота", "Ocelot Egg", "http://media-mcw.cursecdn.com/e/e8/Grid_Spawn_Ocelot.png", null),
  ("383:100", "Яйцо призывания лошади", "Horse Egg", "http://media-mcw.cursecdn.com/e/e0/Grid_Spawn_Horse.png", null),
  ("383:120", "Яйцо призывания деревенского жителя", "Villager Egg", "http://media-mcw.cursecdn.com/0/02/Grid_Spawn_Villager.png", null),
  ("397:0", "Голова скелета", "Skeleton Head", "http://media-mcw.cursecdn.com/c/c9/Grid_Skeleton_Skull.png", null),
  ("397:1", "Голова скелета-иссушителя", "Wither Skeleton Head", "http://media-mcw.cursecdn.com/d/d4/Grid_Wither_Skeleton_Skull.png", null),
  ("397:2", "Голова зомби", "Zombie Head", "http://media-mcw.cursecdn.com/6/6f/Grid_Zombie_Head.png", null),
  ("397:3", "Голова", "Human Head", "http://media-mcw.cursecdn.com/5/55/Grid_Head.png", null),
  ("397:4", "Голова крипера", "Creeper Head", "http://media-mcw.cursecdn.com/c/c7/Grid_Creeper_Head.png", null);
