name: apiserver
version: 0.0.1



config:

    logfile: './main.log'
    pidfile: './main.pid'


    default:

        port: 8001

        db:
            host: 176.31.14.255
            port: 3306

            multipleStatements: true
            timezone: Z


    development:

        installed: false

        db:
            database: apiserver

            user: apiserver
            password: iamthe1337

            debug: true


    production:

        installed: true

        db: # http://red.flydev.net/issues/5#note-3
            database: apiserver

            user: apiserver
            password: iamthe1337

            debug: false




dependencies:

    async: 0.2.9
    extend: 1.1.3

    express: 3.3.7

    passport: 0.1.17

    connect-redis: 1.4.5
    redis: 0.8.4
    mysql: 2.0.0-alpha8

    log: 1.4.0
    request: 2.27.0
    nodemailer: 0.5.2



engines:
    node: <=0.10.17
