name: apiserver
version: 0.0.1



config:

    logfile: './main.log'
    pidfile: './main.pid'


    default:

        port: 8000

        db:
            host: 176.31.14.255
            port: 3306

            timezone: Z

        payment:
            'robokassa':
                merchantUrl: http://test.robokassa.ru/Index.aspx # merchantUrl: https://auth.robokassa.ru/Merchant/Index.aspx
                merchant: awesome39
                pass1: b9f1c6834f49a8e8
                pass2: f4f397e82f26bd34


    development:

        installed: false

        host: local.awesome39.com

        db:
            database: apiserver

            user: apiserver
            password: iamthe1337

            debug: true

        payment:
            'robokassa':
                merchantUrl: http://play.local.awesome39.com:8000/payment/robokassa/debug
                resultUrl: http://play.local.awesome39.com:8000/payment/robokassa/result
                successUrl: http://play.local.awesome39.com:8000/payment/robokassa/success

    production:

        installed: true

        host: flydev.awesome39.com

        db: # http://red.flydev.net/issues/5#note-3
            database: apiserver

            user: apiserver
            password: iamthe1337

            debug: false



scripts:
    start: node node.js



dependencies:

    async: latest
    extend: latest

    express: latest
    jade: latest

    passport: latest

    connect-redis: latest
    redis: latest
    mysql: latest

    log: latest
